# Generated by Django 2.2 on 2023-12-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0004_auto_20231208_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='coach',
            field=models.CharField(default='sleeper', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='from_st',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='to_st',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
