# Generated by Django 2.2 on 2023-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0005_auto_20231208_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='last_login',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
