# Generated by Django 2.2 on 2023-12-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='login_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='login_time',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
