# Generated by Django 2.2 on 2023-12-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0008_auto_20231220_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='login_time',
        ),
    ]
