# Generated by Django 2.2 on 2024-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0009_remove_user_info_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('train_no', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('pnr_no', models.IntegerField()),
                ('coach_no', models.CharField(max_length=10)),
                ('seat_no', models.IntegerField()),
            ],
        ),
    ]
