# Generated by Django 2.2 on 2024-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0010_booking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='pnr_no',
            field=models.CharField(max_length=100),
        ),
    ]
